services:
  - type: web
    name: google-data-analytics-tracker
    env: docker
    plan: free
    region: oregon
    # Render will automatically use the Dockerfile in the root of the repository
    # It will build the image and deploy it based on the exposed port 80
